### ISSUE TITLE
Using the library

### ISSUE THREAD

**Issue by pascalgn** [tuupola/branca-js#1]
I just wanted to let you know that I just added support for Branca in https://github.com/pascalgn/yaml-crypt
Fernet seems a bit unmaintained currently, so thanks for Branca! 👍

**Comment by tuupola** [comment]
Awesome! Let me know if you have any problems. I am mostly using the Python and PHP implementations myself.

**Comment by pascalgn** [comment]
Sure, will raise an issue if I see any problems. So far everything is fine, the API is even a bit nicer than Fernet :)
