### ISSUE TITLE
The 32 byte password style key used to secure branca-js tokens is insecure

### ISSUE THREAD

**Issue by grempe** [tuupola/branca-js#12]
I was surprised that `branca-js` only allows the provision of a "32 byte" key as a **string** of 32 bytes in length (from a set of password chars left up to the user) and not the much more cryptographically secure 32 bytes of actual random bytes (each byte 0-255).

If developers are using the password example you gave (`supersecretkeyyoushouldnotcommit`) and follow this pattern (all lower case) they are only getting `26^32` keyspace which is only 150 bits of entropy, not the required 256. Using a strong password generator to make use of upper, lower, numbers, and special chars still isn't nearly as strong as full bytes. If they generated 32 bytes of random hex (64 chars) they would be getting a `256^32` keyspace which is astronomically harder to brute force.

Using this "password" mechanism, without using a key-derivation function would seem to be an unsafe choice.

https://generatepasswords.org/how-to-calculate-entropy/

Possible combinations:

```js
> 26**32
1.901722457268488e+45
> 256**32
1.157920892373162e+77
```

Entropy

```js
> Math.log2(26**32)
150.41407098051494
> Math.log2(256**32)
256
```

The code change is trivial. Changing `Buffer.from('apasswordstring')` to `Buffer.from('deadbeef', 'hex')`. Of course this would be a breaking change, but a semver major version bump should allow for that in the name of greatly increased security.

https://github.com/tuupola/branca-js/blob/8b696a9d8e5a8051fc7fad0c63c18fb8812c5b14/branca.js#L14

Generating such a key in a node repl is trivial and secure:

```js
> crypto.randomBytes(32).toString('hex')
'7ed049e344f73f399ba1f7868cf9494f4b13347ecce02a8e463feb32507b73a5'
```

Cheers.

**Comment by tuupola** [comment]
Lowercase ASCII key is not a requirement. To use the hex encoded random key from above, you could do something like:

```javascript
const key = Buffer.from("7ed049e344f73f399ba1f7868cf9494f4b13347ecce02a8e463feb32507b73a5", "hex");
const branca = require("branca")(key);

const data = "Hello world!"
const token = branca.encode(data);
const payload = branca.decode(token);

console.log(token);
console.log(payload);
console.log(payload.toString());
```

Which yields:

```
881mp4Bw8Kld1gnoCzLNLAeKJLbLG6FZ5GfTFqWHdFO2BCK66l8pGMznUFU30ZqAqqaD4aphgnW2g
<Buffer 48 65 6c 6c 6f 20 77 6f 72 6c 64 21>
Hello world!
```

**Comment by grempe** [comment]
Thanks for the comment and example. I've taken the liberty of making some additional enhancements that you might consider using instead that will make this secure by default if a 32 byte hex key is passed in, while continuing to work with the insecure password keys. I've also added additional tests for all key types (password, hex, hex w/ 0x prefix). There is no overhead once initialized for using this code. I think that encouraging use of strong keys is a requirement for a security library. The difference in entropy between the password and secure random hex is so significant (but a subtle distinction for many users) that it should be the default. Thanks.

**Comment by tuupola** [comment]
I do not agree with the language the 32 byte key when comprised of ASCII characters is *"insecure"*. It is *"less secure"* than a 32 byte key comprised of bytes. XChaCha20 also does not encrypt directly with the given key. Instead it creates a subkey by hashing the given key and part of the generated nonce with HChaCha20. Libsodium describes the output as:

*"32 byte value indistinguishable from random data without knowing the key."*

So if I understand correctly from cryptanalysis point of view the  secret key entropy does not matter that much since the keystream used to create the ciphertext still has full entropy. Brute forcing is different thing though. Assuming attacker knows the used character set a random ASCII secret key is easier to brute force than random byte secret key. Brute forcing a 32 byte ASCII key would still take a considerable time though. 

That said I am starting to be out of my league here and the above might not be correct. Full entropy key is still the best practice and I do like the shortcut of passing the key as hex. But I will comment the PR in the PR itself.

**Comment by tuupola** [comment]
> Also note that Typescript complains about your suggested technique since it infers that the `key` argument is a string and complains about handing in a Buffer.

Apparently there is an open issue about this:

https://github.com/microsoft/TypeScript/issues/14107
https://github.com/microsoft/TypeScript/issues/23155

**Comment by grempe** [comment]
Thanks, I'll look for your comments in the PR.

LibSodium is clear as to what makes an acceptable secure key (vs a user chosen password).

```
Secret keys are not designed to be typed on a keyboard. This is binary data. They are stored as files, kept in secure memory or sent over the network. They can be unique, and offer far more security than passwords.
Libsodium almost exclusively uses secret keys.
```

https://libsodium.gitbook.io/doc/quickstart#what-is-the-difference-between-a-secret-key-and-a-password

The strength of the existing scheme depends entirely on how the user __chooses__ the password. This is why crypto libraries provide secure randomness generators. User chosen passwords should always pass through a [key derivation algorithm](https://en.m.wikipedia.org/wiki/Key_derivation_function) (e.g. Argon2) to slow brute force attacks when used as a secret key. Random key bytes from a crypto secure PRNG don't require this step.

**Comment by grempe** [comment]
New PR's added to resolve this issue:

#14 

#15 

#16

**Comment by grempe** [comment]
I'd ❤️ a new release.
